//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atele_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_photo
    {
        public int ID_Photo { get; set; }
        public int ID_Client { get; set; }
        public byte[] Photo_binary { get; set; }
        public string Photo_path { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
