//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atele_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Measurements()
        {
            this.Order = new HashSet<Order>();
            this.Order_measurements = new HashSet<Order_measurements>();
        }
    
        public int ID_Measurements { get; set; }
        public Nullable<int> Bust { get; set; }
        public Nullable<int> Waist_circumference { get; set; }
        public Nullable<int> Hip_girth { get; set; }
        public Nullable<int> Neck_girth { get; set; }
        public Nullable<int> Сhest_width { get; set; }
        public Nullable<int> Back_width { get; set; }
        public Nullable<int> Arm_circumference { get; set; }
        public Nullable<int> Wrist_girth { get; set; }
        public Nullable<int> Knee_girth { get; set; }
        public Nullable<int> Foot_size { get; set; }
        public Nullable<int> Growth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_measurements> Order_measurements { get; set; }
    }
}
