//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atele_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_measurement
    {
        public int ID_Order_measurement { get; set; }
        public int ID_Order { get; set; }
        public int ID_Measurement { get; set; }
        public Nullable<int> Size { get; set; }
    
        public virtual Measurement Measurement { get; set; }
        public virtual Order Order { get; set; }
    }
}
