//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atele_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Accessory = new HashSet<Order_Accessory>();
            this.Order_basic_material = new HashSet<Order_basic_material>();
            this.Order_measurement = new HashSet<Order_measurement>();
        }
    
        public int ID_Order { get; set; }
        public int ID_Client { get; set; }
        public int ID_Work { get; set; }
        public Nullable<int> ID_Sotrudnic { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Sotrudnic Sotrudnic { get; set; }
        public virtual Work Work { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Accessory> Order_Accessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_basic_material> Order_basic_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_measurement> Order_measurement { get; set; }
    }
}
