//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atele_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnic()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID_Sotrudnic { get; set; }
        public string Surname_sotrudnic { get; set; }
        public string Firstname_sotrudnic { get; set; }
        public string Patronymic_sotrudnic { get; set; }
        public int ID_Gender { get; set; }
        public int ID_Passport { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public int ID_Education { get; set; }
        public int ID_Qualification { get; set; }
        public int ID_Post { get; set; }
        public string Adress { get; set; }
        public string Mobile_phone { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Post Post { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
